from django.db import models

class Anggota(models.Model):
    AwaldiGPO = models.IntegerField()
    NomorID = models.IntegerField()
    NoAng = models.IntegerField()
    Anak1ID = models.IntegerField()
    Anak2ID = models.IntegerField()
    Anak3ID = models.IntegerField()
    Anak4ID = models.IntegerField()
    VerifyID = models.IntegerField()
    fatherid = models.IntegerField()
    motherid = models.IntegerField()
    spouseid = models.IntegerField()
    CrUser = models.IntegerField()
    ModUser = models.IntegerField()
    DOB = models.DateTimeField()
    AtestasiMasuk = models.DateTimeField()
    AtestasiKeluar = models.DateTimeField()
    TanggalBaptis = models.DateTimeField()
    TanggalSidi = models.DateTimeField()
    Tglverifikasi = models.DateTimeField()
    CrDate = models.DateTimeField()
    ModDate = models.DateTimeField()
    Nama = models.CharField(max_length=45)
    Gender = models.CharField(max_length=6)
    HomeBase = models.CharField(max_length=4)
    TempatLahir = models.CharField(max_length=50)
    StatusAnggota = models.CharField(max_length=50)
    Kategorial = models.CharField(max_length=20)
    Verifyoleh = models.CharField(max_length=45)
    CatatanbukuGPO = models.CharField(max_length=50)
    Groupinterest = models.CharField(max_length=15)
    loginID = models.CharField(max_length=20)
    pwd = models.CharField(max_length=30)
    PasPhotoFile = models.CharField(max_length=255)
    KodeposdiLN = models.CharField(max_length=6)
    NegaradiLN = models.CharField(max_length=30)
    TelpdiLN = models.CharField(max_length=15)
    Remarks = models.CharField(max_length=250)
    verified = models.CharField(max_length=10)
    Yangperludiverifikasi = models.CharField(max_length=80)
    MaritalStatus = models.CharField(max_length=15)
    Wilayah = models.CharField(max_length=10)
    Nomorlama = models.CharField(max_length=5)
    AlamatdiLN1 = models.CharField(max_length=40)
    AlamatdiLN2 = models.CharField(max_length=30)
    KotadiLN = models.CharField(max_length=20)
    Anak2 = models.CharField(max_length=45)
    NomorAnak2 = models.CharField(max_length=5)
    Anak3 = models.CharField(max_length=45)
    NomorAnak3 = models.CharField(max_length=5)
    Anak4 = models.CharField(max_length=45)
    NomorAnak4 = models.CharField(max_length=5)
    NamaSuamiIstri = models.CharField(max_length=45)
    NomorSuamiistri = models.CharField(max_length=5)
    Ayah = models.CharField(max_length=45)
    Ibu = models.CharField(max_length=45)
    Anak1 = models.CharField(max_length=45)
    NomorAnak1 = models.CharField(max_length=5)
    SIDIdiGereja = models.CharField(max_length=100)
    Kewarganegaraan = models.CharField(max_length=30)
    Kewarganegaraanlain = models.CharField(max_length=30)
    LamadiGPOGPBB = models.CharField(max_length=10)
    Pelayanan = models.CharField(max_length=255)
    Talenta = models.CharField(max_length=255)
    TelHome = models.CharField(max_length=15)
    TelMobile = models.CharField(max_length=15)
    Email = models.CharField(max_length=100)
    GerejaAsal = models.CharField(max_length=70)
    StatusBaptis = models.CharField(max_length=50)
    BaptisdiGereja = models.CharField(max_length=100)
    Pekerjaan = models.CharField(max_length=30)
    Alamat1 = models.CharField(max_length=45)
    Alamat2 = models.CharField(max_length=30)
    Kota = models.CharField(max_length=20)
    Negara = models.CharField(max_length=30)
    Kodepos = models.CharField(max_length=6)
    userType = models.CharField(max_length=20)
    StatusKeanggotaan = models.CharField(max_length=10)
    
    class Meta:
        db_table = "Anggota"

    def __unicode__(self):
        return self.nama
